force-app/main/default/objects/Access_Restriction__c/Access_Restriction__c.object-meta.xml
<CustomObject>
    <label>Access Restriction</label>
    <nameField>
        <displayFormat>RES-{000000}</displayFormat>
        <label>Restriction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Restrictions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Access_Restriction__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>SymphonyLF__Client__c</referenceTo>
    <relationshipName>Wall_Of_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Wall_Of_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShareableObjects__mdt/ShareableObjects__mdt.object-meta.xml
<CustomObject>
    <label>ShareableObjects</label>
    <pluralLabel>ShareableObjects</pluralLabel>
</CustomObject>

force-app/main/default/objects/ShareableObjects__mdt/fields/Parent_Relationship_Path__c.field-meta.xml
<CustomField>
    <fullName>Parent_Relationship_Path__c</fullName>
    <label>Parent_Relationship_Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ShareableObjects__mdt/fields/Row_Cause__c.field-meta.xml
<CustomField>
    <fullName>Row_Cause__c</fullName>
    <label>Row_Cause</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ShareableObjects__mdt/fields/Share_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Share_Object_API_Name__c</fullName>
    <label>Share_Object_API_Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserAccessSharingBatch.cls
global class UserAccessSharingBatch implements Database.Batchable<SObject>, Database.RaisesPlatformEvents {
    private Id userId;
    private ShareableObjects__mdt meta;

    // Transients
    private String objectName;
    private String shareObjectName;
    private String rowCause;
    private String clientFieldAPI;

    public UserAccessSharingBatch(Id userId, ShareableObjects__mdt meta) {
        this.userId = userId;
        this.meta = meta;

        this.objectName = meta.MasterLabel;
        this.shareObjectName = meta.Share_Object_API_Name__c;
        this.rowCause = meta.Row_Cause__c;
        this.clientFieldAPI = meta.Parent_Relationship_Path__c;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        // Get access-restricted clients for this user
        Set<Id> restrictedClientIds = new Set<Id>();
        for (Access_Restriction__c ar : [
            SELECT Client__c FROM Access_Restriction__c WHERE User__c = :userId
        ]) {
            restrictedClientIds.add(ar.Client__c);
        }

        // Dynamic SOQL based on metadata
        String query = 'SELECT Id FROM ' + objectName;

        if (clientFieldAPI != null && !restrictedClientIds.isEmpty()) {
            String whereClause = clientFieldAPI + ' NOT IN :restrictedClientIds';
            query += ' WHERE ' + whereClause;
        }

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<SObject> shareRecords = new List<SObject>();

        for (SObject obj : scope) {
            SObject shareObj = (SObject) Type.forName(shareObjectName).newInstance();
            shareObj.put('ParentId', obj.Id);
            shareObj.put('UserOrGroupId', userId);
            shareObj.put('AccessLevel', 'Edit');
            shareObj.put('RowCause', rowCause);
            shareRecords.add(shareObj);
        }

        if (!shareRecords.isEmpty()) {
            Database.SaveResult[] results = Database.insert(shareRecords, false);
            for (Database.SaveResult sr : results) {
                if (!sr.isSuccess()) {
                    for (Database.Error err : sr.getErrors()) {
                        System.debug('Insert failed: ' + err.getMessage());
                    }
                }
            }
        }
    }

    global void finish(Database.BatchableContext bc) {}
}