force-app/main/default/objects/Access_Restriction__c/Access_Restriction__c.object-meta.xml
<CustomObject>
    <label>Access Restriction</label>
    <nameField>
        <displayFormat>RES-{000000}</displayFormat>
        <label>Restriction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Restrictions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Access_Restriction__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>SymphonyLF__Client__c</referenceTo>
    <relationshipName>Wall_Of_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Lookup_Fields__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Fields__c</fullName>
    <description>To store the Id that is related to the Lookup Matter populated
**Not use Client as it has logic to provide sharing**</description>
    <formula>BLANKVALUE(Agreement_and_Contract__c,
BLANKVALUE(Patent__c,
BLANKVALUE(Trademark__c,
BLANKVALUE(Copyright__c,
BLANKVALUE(Design__c,
BLANKVALUE(Dispute_Opposition__c,
BLANKVALUE(General_Matter__c,
NULL
)
)
)
)
)
)
)</formula>
    <label>Lookup Fields Record Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <description>**Picklist API Name should always be object API Name**
As it is used for sharing logic</description>
    <label>ObjectName</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SymphonyLF__Patent__c</fullName>
                <label>Patents</label>
            </value>
            <value>
                <fullName>SymphonyLF__Client__c</fullName>
                <label>Client</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person</label>
    <referenceTo>SymphonyLF__Person__c</referenceTo>
    <relationshipName>Person</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Enforced</fullName>
            </value>
            <value>
                <fullName>Enforced</fullName>
            </value>
            <value>
                <fullName>To Be Granted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RestructuredAccessRestrictionScheduler.cls
/**
 * @description       : To grant / revoke access from the User via Access restrictions 
 * @author            : Pranav G
 * @group             : 
 * @last modified on  : 04-07-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
global without sharing class RestructuredAccessRestrictionScheduler implements Schedulable {
    private static final String TO_BE_GRANTED = 'To Be Granted';
    private static final String TO_BE_ENFORCED = 'To Be Enforced';
    private static final Integer START = 0;

    global void execute(SchedulableContext SC) {
        List<Access_Restriction__c> accessRecords = [SELECT Id, Status__c, Person__r.SymphonyLF__User__c, Client__c, CreatedBy.Email, Client__r.Name, 
                                                        Lookup_Fields__c, ObjectName__c
                                                    FROM Access_Restriction__c
                                                    WHERE Status__c IN (:TO_BE_GRANTED, :TO_BE_ENFORCED)];

        if (!accessRecords.isEmpty()) {
            Database.executeBatch(new RestructuredClientShareControllerbatch(accessRecords , START), 150);
        }
    }
}