force-app/main/default/objects/Access_Restriction__c/Access_Restriction__c.object-meta.xml
<CustomObject>
    <label>Access Restriction</label>
    <nameField>
        <displayFormat>RES-{000000}</displayFormat>
        <label>Restriction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Restrictions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Access_Restriction__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>SymphonyLF__Client__c</referenceTo>
    <relationshipName>Wall_Of_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Enforced</fullName>
            </value>
            <value>
                <fullName>Enforced</fullName>
            </value>
            <value>
                <fullName>To Be Granted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Wall_Of_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conflict_Check__c/Conflict_Check__c.object-meta.xml
<CustomObject>
    <label>Conflict Check</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Conflict Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conflict Checks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Conflict_Check__c/fields/Adverse_Parties__c.field-meta.xml
<CustomField>
    <fullName>Adverse_Parties__c</fullName>
    <label>Adverse Parties</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conflict_Check__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>SymphonyLF__Client__c</referenceTo>
    <relationshipLabel>Conflict Check Clients</relationshipLabel>
    <relationshipName>Conflict_Check_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conflict_Check__c/fields/Contributor__c.field-meta.xml
<CustomField>
    <fullName>Contributor__c</fullName>
    <label>Contributors</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Conflict_Check__c/fields/Keywords__c.field-meta.xml
<CustomField>
    <fullName>Keywords__c</fullName>
    <label>Keywords</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Conflict_Check__c/fields/Related_Parties_other_than_client__c.field-meta.xml
<CustomField>
    <fullName>Related_Parties_other_than_client__c</fullName>
    <label>Related Parties other than client</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConflictCheckTriggerHandler.cls
public with sharing class ConflictCheckTriggerHandler extends mvSObjectDomain{
    Map<Id, Conflict_Check__c> oldMap;
    List<Conflict_Check__c> newRecords;
    Map<Id, Conflict_Check__c> newMap;

    public ConflictCheckTriggerHandler(List<Conflict_Check__c> sObjectList) {
        super(sObjectList);
    }

    public class Constructor implements mvSObjectDomain.IConstructable {
        public mvSObjectDomain construct(List<SObject> sObjectList) {
            return new ConflictCheckTriggerHandler(sObjectList);
        }
    }

    Set<Id> runSearchResult= new Set<Id>();

    public override void onAfterInsert(){
        this.newRecords = (List<Conflict_Check__c>) records;
        this.newMap = new Map<Id, Conflict_Check__c>(this.newRecords);

        for(Conflict_Check__c newRecord : this.newRecords){
            runSearchResult(newRecord, null);
        }

        if(runSearchResult.size() > 0){
            createTasks();
            runSearchResult();
        }
    }

    public override void onAfterUpdate(Map<Id, SObject> existingRecords){
        this.newRecords = (List<Conflict_Check__c>) records;
        this.newMap = new Map<Id, Conflict_Check__c>(this.newRecords);
        this.oldMap = (Map<Id, Conflict_Check__c>) existingRecords;

        for(Conflict_Check__c newRecord : this.newRecords){
            Conflict_Check__c oldRecord = this.oldMap.get(newRecord.Id);
            runSearchResult(newRecord, oldRecord);
        }

        if(runSearchResult.size() > 0){
            runSearchResult();
        }
    }

    static Set<String> runSearchResultTrackedFiedls = new Set<String>{
        'Adverse_Parties__c',
        'Related_Parties_other_than_client__c',
        'Contributor__c',
        'Keywords__c',
        'Client_Name__c'
    };

    void runSearchResult(Conflict_Check__c newRecord, Conflict_Check__c oldRecord){
        if(
            oldRecord == null
        ){
            runSearchResult.add( newRecord.Id );
            return;
        }

        sObject newR = newRecord;
        sObject oldR = oldRecord;

        for(String field : runSearchResultTrackedFiedls){
            if(newR.get(field) != oldR.get(field)){
                runSearchResult.add( newRecord.Id );
                break;
            }
        }
    }

    void runSearchResult(){
        for(Id i : runSearchResult){
            ConflictCheckSearchResultService c = new ConflictCheckSearchResultService();
            c.setOperationType(ConflictCheckSearchResultService.OperationType.DELETE_AND_SEARCH);
            c.setConflictCheck(this.newmap.get(i));
            c.execute();
        }
    }

    void createTasks(){
        Set<String> userLicenseAllowed = new Set<String>{
            'Salesforce Platform',
            'Salesforce'
        };

        Set<String> profilesNotToInclude = new Set<String>{
            'Account and Finance Team',
            'System Administrator',
            'Client',
            'Chatter Free User',
            'API Only User'
        };
        Set<Id> ccIds = new Set<Id>();
            
        Set<Id> wallUserIds = new Set<Id>();
        for(Conflict_Check__c conflictCheck : this.newRecords){
            ccIds.add(conflictCheck.Id);
        }
        for(Conflict_Check__c conflictCheckRecord: this.newRecords){
            if(conflictCheckRecord.Client_Name__c <> Null){
                wallUserIds.add(conflictCheckRecord.Client_Name__c);}
        }
         if(wallUserIds.size()>0){
            for(Access_Restriction__c wallOfuser : [SELECT id,User__c FROM Access_Restriction__c WHERE Status__c = 'Enforced' and Client__c IN : wallUserIds]){
                if(wallOfuser.User__c <> Null){
                    wallUserIds.add(wallOfuser.User__c);}
            } 
      } 

        List<Task> list_tasks = new List<Task>();

        List<User> list_users = [
            SELECT 
                Id, Profile.Name,Profile.UserLicense.Name,isActive
            FROM 
                User 
            WHERE 
                isActive = true 
                AND 
                Profile.UserLicense.Name IN : userLicenseAllowed 
                AND 
                profile.Name NOT IN :profilesNotToInclude 
                AND 
                ID !=: UserInfo.getUserId()
                AND 
                ID NOT IN : wallUserIds
        ];
           
        if(!list_users.isEmpty()){
            String lockIdValue = 'Conflict check Record Acess To All Users Lock';
            //LockerService.applyLocksAcrossServices(lockIdValue);
            List<Conflict_Check__c> conflictcheck = [Select Id,name,Client_Name__r.Originating_Attorney__r.SymphonyLF__User__c From Conflict_Check__c Where Id IN :ccIds ];
            if(!conflictcheck.isEmpty() ){
            for(Conflict_Check__c conflictCheckRecord: conflictcheck){
                for(User userRecord : list_users){
                    System.debug('conflictCheckRecord---->'+conflictCheckRecord);
                    System.debug('userRecord.Id----->'+userRecord.Id);
                    if(conflictCheckRecord.Client_Name__r.Originating_Attorney__r.SymphonyLF__User__c != userRecord.Id){
                        list_tasks.add(
                            new Task(
                                WhatId = conflictCheckRecord.Id,
                                OwnerId = userRecord.id,
                                ForId__c = userRecord.id,
                                Subject = 'Approve / Discuss for the client for this Conflict Check '+conflictCheckRecord.name,
                                Status = 'Not Yet Started',
                                ActivityDate = Date.today() + 13
                            )
                        );
                    }

                   /* ApexSharingService a = new ApexSharingService();
                    a.setModuleName('After create Conflict Check record through Form');
                    a.setShareObject('Conflict_Check__Share');
                    a.setRecordId(conflictCheckRecord.Id);
                    a.setUserIds(new Set<Id>{ userRecord.id });
                    a.setRowCause('Manual');
                    String accessLevel = conflictCheckRecord.Client_Name__r.Originating_Attorney__r.SymphonyLF__User__c != userRecord.Id ? 'Read' : 'Edit'; 
                    system.debug('accessLevel++'+ accessLevel);
                    a.setAccessLevel(accessLevel);
                    a.addShare();*/
                }    
            }
        }
            
            //LockerService.releaseLockAcrossServices(lockIdValue);
        }
        if(!list_tasks.isEmpty()){
            insert list_tasks;
        }
    }
}