force-app/main/default/objects/Access_Restriction__c/Access_Restriction__c.object-meta.xml
<CustomObject>
    <label>Access Restriction</label>
    <nameField>
        <displayFormat>RES-{000000}</displayFormat>
        <label>Restriction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Restrictions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Access_Restriction__c/fields/Agreement_and_Contract__c.field-meta.xml
<CustomField>
    <fullName>Agreement_and_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agreement and Contract</label>
    <referenceTo>SymphonyLF__Agreement_Contract__c</referenceTo>
    <relationshipName>Wall_Of_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>SymphonyLF__Client__c</referenceTo>
    <relationshipName>Wall_Of_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Copyright__c.field-meta.xml
<CustomField>
    <fullName>Copyright__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Copyright</label>
    <referenceTo>SymphonyLF__Copyright__c</referenceTo>
    <relationshipName>Wall_Of_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Design__c.field-meta.xml
<CustomField>
    <fullName>Design__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Design</label>
    <referenceTo>SymphonyLF__Design__c</referenceTo>
    <relationshipName>Wall_Of_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Design_Family__c.field-meta.xml
<CustomField>
    <fullName>Design_Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Design Family</label>
    <referenceTo>SymphonyLF__Design_Family__c</referenceTo>
    <relationshipLabel>Access Restrictions</relationshipLabel>
    <relationshipName>Access_Restrictions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Dispute_Opposition__c.field-meta.xml
<CustomField>
    <fullName>Dispute_Opposition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dispute/Opposition</label>
    <referenceTo>SymphonyLF__Dispute_Opposition__c</referenceTo>
    <relationshipName>Wall_Of_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Mark__c.field-meta.xml
<CustomField>
    <fullName>Mark__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mark</label>
    <referenceTo>SymphonyLF__Mark__c</referenceTo>
    <relationshipLabel>Access Restrictions</relationshipLabel>
    <relationshipName>Access_Restrictions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Patent__c.field-meta.xml
<CustomField>
    <fullName>Patent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patent</label>
    <referenceTo>SymphonyLF__Patent__c</referenceTo>
    <relationshipName>Wall_Of_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Patent_Family__c.field-meta.xml
<CustomField>
    <fullName>Patent_Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patent Family</label>
    <referenceTo>SymphonyLF__Patent_Family__c</referenceTo>
    <relationshipLabel>Access Restrictions</relationshipLabel>
    <relationshipName>Access_Restrictions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person</label>
    <referenceTo>SymphonyLF__Person__c</referenceTo>
    <relationshipName>Person</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Enforced</fullName>
            </value>
            <value>
                <fullName>Enforced</fullName>
            </value>
            <value>
                <fullName>To Be Granted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Trademark__c.field-meta.xml
<CustomField>
    <fullName>Trademark__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trademark</label>
    <referenceTo>SymphonyLF__Trademark__c</referenceTo>
    <relationshipName>Wall_Of_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Access_Restriction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Patent</fullName>
            </value>
            <value>
                <fullName>Trademark</fullName>
            </value>
            <value>
                <fullName>Copyright</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Dispute/Opposition</fullName>
            </value>
            <value>
                <fullName>Agreement and Contract</fullName>
            </value>
            <value>
                <fullName>Patent Family</fullName>
            </value>
            <value>
                <fullName>Design Family</fullName>
            </value>
            <value>
                <fullName>Mark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccessRestrictionScheduler.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-06-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
global without sharing class AccessRestrictionScheduler implements Schedulable {

    private static final String TO_BE_GRANTED = 'To Be Granted';
    private static final String TO_BE_ENFORCED = 'To Be Enforced';
    private static final String PATENT = 'Patent';
    private static final String CLIENT = 'Client';
    private static final String TRADEMARK = 'Trademark';
    private static final String COPYRIGHT = 'Copyright';
    private static final String DESIGN = 'Design';
    private static final String DISPUTE = 'Dispute/Opposition';
    private static final String AGREEMENTCONTRACT = 'Agreement and Contract';
    private static final String PATENTFAMILY = 'Patent Family';
    private static final String DESIGNFAMILY = 'Design Family';
    private static final String MARK = 'Mark';
    global void execute(SchedulableContext SC) {
        List<Access_Restriction__c> accessRecords = [SELECT Id, Type__c, Patent_Family__c, Design_Family__c, Mark__c, Patent__c, Trademark__c, Design__c, Copyright__c, Agreement_and_Contract__c, Dispute_Opposition__c, Status__c, Person__r.SymphonyLF__User__c, Client__c, CreatedBy.Email, Client__r.Name
                                                        FROM Access_Restriction__c
                                                        WHERE Status__c IN (:TO_BE_GRANTED, :TO_BE_ENFORCED)];

        Map<Id,Id> grantAccess = new Map<Id,Id>();
        Map<Id,Id> removeAccess = new Map<Id,Id>();
        Map<String,Access_Restriction__c> accessRecordMap = new Map<String,Access_Restriction__c>();

        for (Access_Restriction__c record : accessRecords) {
            if (record.Person__r.SymphonyLF__User__c != null && record.Client__c != null) {
                system.debug(record.Type__c);
              Id objectId = record.Type__c == PATENT ? record.Patent__c 
              : record.Type__c == CLIENT ? record.Client__c 
              : record.Type__c == TRADEMARK ? record.Trademark__c 
              : record.Type__c == COPYRIGHT ? record.Copyright__c
              : record.Type__c == DESIGN ? record.Design__c
              : record.Type__c == AGREEMENTCONTRACT ? record.Agreement_and_Contract__c
              : record.Type__c == DISPUTE ? record.Dispute_Opposition__c
              : record.Type__c == PATENTFAMILY ? record.Patent_Family__c
              : record.Type__c == DESIGNFAMILY ? record.Design_Family__c
              : record.Type__c == MARK ? record.Mark__c
              : null; 

             accessRecordMap.put( String.valueOf(record.Person__r.SymphonyLF__User__c)+String.valueOf(objectId) , record);
              if (record.Status__c == TO_BE_GRANTED) {
                    grantAccess.put(record.Person__r.SymphonyLF__User__c , objectId);
                  } else if (record.Status__c == TO_BE_ENFORCED) {
                    removeAccess.put(record.Person__r.SymphonyLF__User__c , objectId);
                 }
            }
        }

        if (!grantAccess.isEmpty()) {
            for (Id userId : grantAccess.keySet()) {
                Id clientId = grantAccess.get(userId);
                Access_Restriction__c record = accessRecordMap.get(String.valueOf(userId)+String.valueOf(clientId));
                ClientShareControllerBatch grantBatch = new ClientShareControllerBatch(false, userId, clientId, new List<Access_Restriction__c>{record});
                Database.executeBatch(grantBatch, 150);
            }
        }

        if (!removeAccess.isEmpty()) {
            for (Id userId : removeAccess.keySet()) {
                Id clientId = removeAccess.get(userId);
                Access_Restriction__c record = accessRecordMap.get(String.valueOf(userId)+String.valueOf(clientId));
                ClientShareControllerBatch removeBatch = new ClientShareControllerBatch(true, userId, clientId, new List<Access_Restriction__c>{record});
                Database.executeBatch(removeBatch, 200);
            }
        }
    }
}