force-app/main/default/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <label>Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist__c/fields/Checklist__c.field-meta.xml
<CustomField>
    <fullName>Checklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(Legacy)Checklist</label>
    <referenceTo>Checklist__c</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Design__c.field-meta.xml
<CustomField>
    <fullName>Design__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(Legacy)Design</label>
    <referenceTo>SymphonyLF__Design__c</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Patent__c.field-meta.xml
<CustomField>
    <fullName>Patent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(Legacy)Patent</label>
    <referenceTo>SymphonyLF__Patent__c</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance__c/Checklist_Instance__c.object-meta.xml
<CustomObject>
    <label>Checklist Instance</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Checklist Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Instance__c/fields/Attorney__c.field-meta.xml
<CustomField>
    <fullName>Attorney__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attorney</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Attorney</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Checklist_Instances1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance__c/fields/Checklist__c.field-meta.xml
<CustomField>
    <fullName>Checklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist</label>
    <referenceTo>Checklist__c</referenceTo>
    <relationshipLabel>Checklist Instances</relationshipLabel>
    <relationshipName>Checklist_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance__c/fields/Design__c.field-meta.xml
<CustomField>
    <fullName>Design__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Design</label>
    <referenceTo>SymphonyLF__Design__c</referenceTo>
    <relationshipLabel>Checklist Instances</relationshipLabel>
    <relationshipName>Checklist_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance__c/fields/Double_Checker__c.field-meta.xml
<CustomField>
    <fullName>Double_Checker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Double Checker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Double_Checker__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Checklist_Instances2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance__c/fields/Double_Checker_Completed__c.field-meta.xml
<CustomField>
    <fullName>Double_Checker_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Double Checker Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance__c/fields/Double_Checker_Notes__c.field-meta.xml
<CustomField>
    <fullName>Double_Checker_Notes__c</fullName>
    <label>Double Checker Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance__c/fields/Patent__c.field-meta.xml
<CustomField>
    <fullName>Patent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patent</label>
    <referenceTo>SymphonyLF__Patent__c</referenceTo>
    <relationshipLabel>Checklist Instances</relationshipLabel>
    <relationshipName>Checklist_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance__c/fields/Secretary__c.field-meta.xml
<CustomField>
    <fullName>Secretary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secretary</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Legal Assistant</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Paralegal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Checklist_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance__c/fields/Secretary_Completed__c.field-meta.xml
<CustomField>
    <fullName>Secretary_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Secretary Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Assignment Checklist In Progress</fullName>
            </value>
            <value>
                <fullName>Attorney Checklist In Progress</fullName>
            </value>
            <value>
                <fullName>Filing Documents with PTO</fullName>
            </value>
            <value>
                <fullName>Double Checking</fullName>
            </value>
            <value>
                <fullName>Double Checker Approved</fullName>
            </value>
            <value>
                <fullName>Modification In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Checklist_Instance_Item__c/Checklist_Instance_Item__c.object-meta.xml
<CustomObject>
    <label>Checklist Instance Item</label>
    <nameField>
        <displayFormat>CII - {000000}</displayFormat>
        <label>Checklist Instance Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Instance Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Instance_Item__c/fields/Attorney_Completed__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attorney Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance_Item__c/fields/Checklist_Instance__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Instance__c</fullName>
    <label>Checklist Instance</label>
    <referenceTo>Checklist_Instance__c</referenceTo>
    <relationshipLabel>Checklist Instance Items</relationshipLabel>
    <relationshipName>Checklist_Instance_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance_Item__c/fields/Checklist_Item__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist Item</label>
    <referenceTo>Checklist_Item__c</referenceTo>
    <relationshipLabel>Checklist Instance Items</relationshipLabel>
    <relationshipName>Checklist_Instance_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/Checklist_Item__c.object-meta.xml
<CustomObject>
    <label>Checklist Item</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>Checklist Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Item__c/fields/Checklist__c.field-meta.xml
<CustomField>
    <fullName>Checklist__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Checklist</label>
    <referenceTo>Checklist__c</referenceTo>
    <relationshipLabel>Checklist Item</relationshipLabel>
    <relationshipName>Checklist_Item</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Section__c/Checklist_Section__c.object-meta.xml
<CustomObject>
    <label>Checklist Section</label>
    <nameField>
        <label>Checklist Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Section__c/fields/Checklist__c.field-meta.xml
<CustomField>
    <fullName>Checklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist</label>
    <referenceTo>Checklist__c</referenceTo>
    <relationshipLabel>Checklist Sections</relationshipLabel>
    <relationshipName>Checklist_Section</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Section__c/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <label>Icon Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>standard:account</fullName>
            </value>
            <value>
                <fullName>standard:question_feed</fullName>
            </value>
            <value>
                <fullName>standard:poll</fullName>
            </value>
            <value>
                <fullName>action:question_post_action</fullName>
            </value>
            <value>
                <fullName>standard:display_text</fullName>
            </value>
            <value>
                <fullName>standard:home</fullName>
            </value>
            <value>
                <fullName>standard:record_consent</fullName>
            </value>
            <value>
                <fullName>standard:task</fullName>
            </value>
            <value>
                <fullName>standard:product_transfer_state</fullName>
            </value>
            <value>
                <fullName>standard:assignment</fullName>
            </value>
            <value>
                <fullName>standard:customers</fullName>
            </value>
            <value>
                <fullName>standard:bundle_policy</fullName>
            </value>
            <value>
                <fullName>standard:entitlement_policy</fullName>
            </value>
            <value>
                <fullName>standard:document_preview</fullName>
            </value>
            <value>
                <fullName>standard:product_request</fullName>
            </value>
            <value>
                <fullName>standard:location</fullName>
            </value>
            <value>
                <fullName>standard:entity</fullName>
            </value>
            <value>
                <fullName>utility:money</fullName>
            </value>
            <value>
                <fullName>standard:sales_value</fullName>
            </value>
            <value>
                <fullName>standard:entitlement</fullName>
            </value>
            <value>
                <fullName>standard:campaign</fullName>
            </value>
            <value>
                <fullName>standard:data_graph</fullName>
            </value>
            <value>
                <fullName>standard:related_list</fullName>
            </value>
            <value>
                <fullName>standard:attach</fullName>
            </value>
            <value>
                <fullName>standard:impact_strategy_assignment</fullName>
            </value>
            <value>
                <fullName>standard:datashares</fullName>
            </value>
            <value>
                <fullName>standard:folder</fullName>
            </value>
            <value>
                <fullName>standard:report</fullName>
            </value>
            <value>
                <fullName>standard:record_create</fullName>
            </value>
            <value>
                <fullName>standard:photo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Checklist_Section__c/fields/Section_Notes__c.field-meta.xml
<CustomField>
    <fullName>Section_Notes__c</fullName>
    <label>Section Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Checklist_Section__c/fields/Section_Type__c.field-meta.xml
<CustomField>
    <fullName>Section_Type__c</fullName>
    <label>Section Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Select</fullName>
            </value>
            <value>
                <fullName>Multi Select</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Checklist_Section__c/fields/Submit_By_Attorney__c.field-meta.xml
<CustomField>
    <fullName>Submit_By_Attorney__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit By Attorney</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_Section__c/fields/Submit_By_Double_Checker__c.field-meta.xml
<CustomField>
    <fullName>Submit_By_Double_Checker__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit By Double Checker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_Section__c/fields/Submit_By_Secretory__c.field-meta.xml
<CustomField>
    <fullName>Submit_By_Secretory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit By Secretory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CL_ChecklistService.cls
public inherited sharing class CL_ChecklistService {
    private String CHECKLIST_INSTANCE_ITEM_OBJECT_NAME = 'Checklist_Instance_Item__c';
    private Map <String, Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();
    private Id currentUserId = UserInfo.getUserId();
    private static CL_ChecklistService serviceInstance;
    public static CL_ChecklistService instance() {
        if(serviceInstance == null) {
            serviceInstance = new CL_ChecklistService();
        }

        return serviceInstance;
    }
    
    public object getCheckListConfigData(String checklistInstanceId){
        return new Map<String, Object> {
            'checklistInstance' => getChecklistInstance(checklistInstanceId)
        };
    }

    public object getSectionList(String checklistInstanceId){
        Map<string, Object> responseMap = new Map<String, Object>();

        Map<String, Object> checklistInstanceRec = getChecklistInstance(checklistInstanceId);
        responseMap.put('sectionList', getSectionListHelper((String)checklistInstanceRec.get('checklistId')));
        
        return responseMap;
    }

    public object getSubSectionList(String checklistInstanceId, String parentSectionId){
        return new Map<String, Object> {
            'subSectionList' => getSubSectionListHelper(checklistInstanceId, parentSectionId)
        };
    }

    private Map<String, Object> getChecklistInstance(String recordId) {
        return buildChecklistInstanceData([SELECT Status__c, Checklist__c, Checklist__r.Name, Secretary_Completed__c, Attorney_Completed__c, Double_Checker_Completed__c, Double_Checker_Notes__c, Secretary__c, Attorney__c, Double_Checker__c, Patent__c, Design__c, Name, Id FROM Checklist_Instance__c WHERE Id =: recordId]);
    }

    private Map<String, Object> buildChecklistInstanceData(Checklist_Instance__c checklistInstance) {
        return new Map<String, Object> {
            'id' => checklistInstance.Id,
            'status' => checklistInstance.Status__c,
            'secretaryCompleted' => checklistInstance.Secretary_Completed__c,
            'checklistId' => checklistInstance.Checklist__c,
            'attorneyCompleted' => checklistInstance.Attorney_Completed__c,
            'doubleCheckerCompleted' => checklistInstance.Double_Checker_Completed__c,
            'secretaryId' => checklistInstance.Secretary__c,
            'attorneyId' => checklistInstance.Attorney__c,
            'doubleCheckerId' => checklistInstance.Double_Checker__c,
            'patentId' => checklistInstance.Patent__c,
            'designId' => checklistInstance.Design__c,
            'formName' => checklistInstance.Checklist__r.Name,
            'isSecretary' => currentUserId == checklistInstance.Secretary__c,
            'isAttorney' => currentUserId == checklistInstance.Attorney__c,
            'isDoubleChecker' => currentUserId == checklistInstance.Double_Checker__c,
            'doubleCheckerNotes' => checklistInstance.Double_Checker_Notes__c
        };
    } 

    private Object getSubsectionListHelper(String checklistInstanceId, String parentSectionId) {
        Set<String> fieldList = getAllChecklistInstanceFields();

        String query = '';
        query += 'SELECT ';
        query += ' Id, Name, Section_Type__c, Submit_By_Attorney__c, Submit_By_Double_Checker__c, Submit_By_Secretory__c, Icon_Name__c, Section_Notes__c, ';
        query += '( ';
        query += 'SELECT ';
        query += ' Checklist_Item__r.Display_Text__c, Checklist_Item__r.Dynamic_Fields__c, Checklist_Item__r.Help_Text__c, ';
        query += String.join(fieldList, ', ');
        query += ' FROM Checklist_Instance_Items__r ';
        query += ' WHERE Checklist_Instance__c =:checklistInstanceId ';
        query += ' ORDER BY Checklist_Item__r.Order__c NULLS LAST ';
        query += ' ) ';
        query += ' FROM Checklist_Section__c ';
        query += ' WHERE Parent_Section__c =: parentSectionId ';
        query += ' ORDER BY Order__c NULLS LAST ';
        query += ' LIMIT 10000 ';

        return buildSubSectionData(Database.query(query));
    }

    private Object buildSubSectionData(List<Checklist_Section__c> sectionList) {
        List<Object> objectList = new List<Object>();

        for(Checklist_Section__c section: sectionList) {
            objectList.add(new Map<String, Object> {
                'id' => section.Id,
                'label' => section.Name,
                'type' => section.Section_Type__c,
                'iconName' => section.Icon_Name__c,
                'submitByAttorney' => section.Submit_By_Attorney__c,
                'submitByDoubleChecker' => section.Submit_By_Double_Checker__c,
                'submitBySecretory' => section.Submit_By_Secretory__c,
                'sectionNotes' => section.Section_Notes__c,
                'itemList' => buildItemList(section.Checklist_Instance_Items__r)
            });
        }

        return objectList;
    }

    private Object buildItemList(List<Checklist_Instance_Item__c> instanceItemList) {
        List<Object> objectList = new List<Object>();

        for(Checklist_Instance_Item__c instanceItem: instanceItemList) {
            objectList.add(new Map<String, Object> {
                'id' => instanceItem.Id,
                'displayText' => instanceItem.Checklist_Item__r.Display_Text__c,
                'helpText' => instanceItem.Checklist_Item__r.Help_Text__c,
                'dynamicFields' => instanceItem.Checklist_Item__r.Dynamic_Fields__c != null ? buildDynamicFieldMapping(instanceItem) : new List<String>(),
                'secretoryCompleted' => instanceItem.Secretary_Completed__c,
                'attorneyCompleted' => instanceItem.Attorney_Completed__c,
                'doubleCheckerCompleted' => instanceItem.Double_Checker_Completed__c
            });
        }

        return objectList;
    }

    private Object getSectionListHelper(String checklistId) {
        return buildSectionData([SELECT Id, Name, Checklist__c FROM Checklist_Section__c WHERE Checklist__c =: checklistId AND Parent_Section__c = null ORDER BY Order__c NULLS LAST LIMIT 10000]);
    }

    private Object buildSectionData(List<Checklist_Section__c> sectionList) {
        List<Object> objectList = new List<Object>();

        for(Checklist_Section__c section: sectionList) {
            objectList.add(new Map<String, Object> {
                'id' => section.Id,
                'label' => section.Name,
                'checklistId' => section.Checklist__c
            });
        }

        return objectList;
    }

    private Object buildDynamicFieldMapping(Checklist_Instance_Item__c instanceItem) {
        List<Object> objectList = new List<Object>();

        sObject sObjRec = instanceItem;
        for(String str: instanceItem.Checklist_Item__r.Dynamic_Fields__c.split(',')) {
            Schema.DescribeFieldResult fieldDescribe = getTypeByApiName(str.trim());
            objectList.add(new Map<String, Object> {
                'apiName' => str.trim(),
                'type' => String.valueOf(fieldDescribe.getType()),
                'helpText' => fieldDescribe.getInlineHelpText(),
                'value' => fieldDescribe.getType() == Schema.DisplayType.MULTIPICKLIST ? getValuesList(sObjRec.get(str.trim())) : sObjRec.get(str.trim()),
                'label' => fieldDescribe.getLabel(),
                'options' => fieldDescribe.getType() == Schema.DisplayType.PICKLIST || fieldDescribe.getType() == Schema.DisplayType.MULTIPICKLIST ? buildPicklistOptions(fieldDescribe.getPicklistValues()) : null,
                'maxLength' => fieldDescribe.getLength()
            });
        }

        return objectList;
    }

    private Schema.DescribeFieldResult getTypeByApiName(String fieldApiName) {
        Map<String, Schema.SObjectField> fieldsMap = getAllFieldsByObjectName(CHECKLIST_INSTANCE_ITEM_OBJECT_NAME);
        Schema.SObjectField field = fieldsMap.get(fieldApiName);
        return field.getDescribe();
    }

    private Set<String> getAllChecklistInstanceFields() {
        return  getAllFieldsByObjectName(CHECKLIST_INSTANCE_ITEM_OBJECT_NAME).keyset(); 
    }

    private Map<String, Schema.SObjectField> getAllFieldsByObjectName(String objectName) {
        Schema.SObjectType sobjType = globalDescribe.get(objectName);
        Schema.DescribeSObjectResult sObjectResultDescribe = sobjType.getDescribe();
        return sObjectResultDescribe.fields.getMap();
    }

    private Object buildPicklistOptions(List<Schema.PicklistEntry> picklistEntryList) {
        List<Object> objectList = new List<Object>();

        for(Schema.PicklistEntry entry: picklistEntryList) {
            objectList.add(new Map<String, Object> {
                'label' => entry.getLabel(),
                'value' => entry.getValue()
            });
        }

        return objectList;
    }

    private Object getValuesList(Object value) {
        if(value == null) return new List<String>();

        return ((String)value).split(';');
    }
    
}