force-app/main/default/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <label>Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist__c/fields/Checklist__c.field-meta.xml
<CustomField>
    <fullName>Checklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(Legacy)Checklist</label>
    <referenceTo>Checklist__c</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Checklist_Code__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Code__c</fullName>
    <label>Checklist Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Checklist_Instance__c/Checklist_Instance__c.object-meta.xml
<CustomObject>
    <label>Checklist Instance</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Checklist Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Instance__c/fields/Checklist__c.field-meta.xml
<CustomField>
    <fullName>Checklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist</label>
    <referenceTo>Checklist__c</referenceTo>
    <relationshipLabel>Checklist Instances</relationshipLabel>
    <relationshipName>Checklist_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance__c/fields/Secretary_Completed__c.field-meta.xml
<CustomField>
    <fullName>Secretary_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Secretary Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Assignment Checklist In Progress</fullName>
            </value>
            <value>
                <fullName>Attorney Checklist In Progress</fullName>
            </value>
            <value>
                <fullName>Filing Documents with PTO</fullName>
            </value>
            <value>
                <fullName>Double Checking</fullName>
            </value>
            <value>
                <fullName>Double Checker Approved</fullName>
            </value>
            <value>
                <fullName>Modification In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Checklist_Instance_Item__c/Checklist_Instance_Item__c.object-meta.xml
<CustomObject>
    <label>Checklist Instance Item</label>
    <nameField>
        <displayFormat>CII - {000000}</displayFormat>
        <label>Checklist Instance Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Instance Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Instance_Item__c/fields/Checklist_Instance__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Instance__c</fullName>
    <label>Checklist Instance</label>
    <referenceTo>Checklist_Instance__c</referenceTo>
    <relationshipLabel>Checklist Instance Items</relationshipLabel>
    <relationshipName>Checklist_Instance_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance_Item__c/fields/Checklist_Item__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist Item</label>
    <referenceTo>Checklist_Item__c</referenceTo>
    <relationshipLabel>Checklist Instance Items</relationshipLabel>
    <relationshipName>Checklist_Instance_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance_Item__c/fields/Checklist_Section__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist Section</label>
    <referenceTo>Checklist_Section__c</referenceTo>
    <relationshipLabel>Checklist Instance Items</relationshipLabel>
    <relationshipName>Checklist_Instance_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Instance_Item__c/fields/Disclosure_date__c.field-meta.xml
<CustomField>
    <fullName>Disclosure_date__c</fullName>
    <label>Disclosure date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/Checklist_Item__c.object-meta.xml
<CustomObject>
    <label>Checklist Item</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>Checklist Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Item__c/fields/Checklist__c.field-meta.xml
<CustomField>
    <fullName>Checklist__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Checklist</label>
    <referenceTo>Checklist__c</referenceTo>
    <relationshipLabel>Checklist Item</relationshipLabel>
    <relationshipName>Checklist_Item</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/fields/Checklist_Section__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist Section</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Checklist_Section__c.Checklist__c</field>
            <operation>equals</operation>
            <valueField>$Source.Checklist__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Checklist_Section__c</referenceTo>
    <relationshipLabel>Checklist Item</relationshipLabel>
    <relationshipName>Checklist_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/fields/Display_Text__c.field-meta.xml
<CustomField>
    <fullName>Display_Text__c</fullName>
    <label>Display Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/fields/Dynamic_Fields__c.field-meta.xml
<CustomField>
    <fullName>Dynamic_Fields__c</fullName>
    <label>Dynamic Fields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <label>Help Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Checklist_Section__c/Checklist_Section__c.object-meta.xml
<CustomObject>
    <label>Checklist Section</label>
    <nameField>
        <label>Checklist Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Section__c/fields/Checklist__c.field-meta.xml
<CustomField>
    <fullName>Checklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist</label>
    <referenceTo>Checklist__c</referenceTo>
    <relationshipLabel>Checklist Sections</relationshipLabel>
    <relationshipName>Checklist_Section</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Section__c/fields/Parent_Section__c.field-meta.xml
<CustomField>
    <fullName>Parent_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Section</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Checklist_Section__c.Checklist__c</field>
            <operation>equals</operation>
            <valueField>$Source.Checklist__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Checklist_Section__c</referenceTo>
    <relationshipLabel>Checklist Sections</relationshipLabel>
    <relationshipName>Checklist_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CL_ChecklistControllerTest.cls
@isTest
public class CL_ChecklistControllerTest {
    @testSetup
    static void setupData() {
        Checklist__c checklist = new Checklist__c (
            Name = 'Test Checklist', 
            Checklist_Code__c = 'Test Checklist Code');
        INSERT checklist;

        Checklist_Instance__c checklistInstance = new Checklist_Instance__c (
            Checklist__c = checklist.Id,
            Status__c = 'Initial Assignment Checklist In Progress'
        );
        INSERT checklistInstance;

        Checklist_Section__c PatenSection = new Checklist_Section__c (
            Name = 'Parent Section',
            Checklist__c = checklist.Id
        );
        INSERT PatenSection;

        Checklist_Section__c childSection = new Checklist_Section__c (
            Name = 'Child Section',
            Checklist__c = checklist.Id,
            Parent_Section__c = PatenSection.Id
        );
        INSERT childSection;

        Checklist_Item__c checkListItem = new Checklist_Item__c (
            Checklist__c = checklist.Id,
            Checklist_Section__c = childSection.Id,
            Display_Text__c = 'Sample Display Text',
            Dynamic_Fields__c = 'Disclosure_date__c',
            Help_Text__c = 'Sample Help Text'
        );
        INSERT checkListItem;

        Checklist_Instance_Item__c instanceItem = new Checklist_Instance_Item__c (
            Checklist_Instance__c = checklistInstance.Id,
            Secretary_Completed__c = false,
            Checklist_Section__c = childSection.Id,
            Checklist_Item__c = checkListItem.Id
        );
        INSERT instanceItem;
    }

    @isTest
    static void testGetCheckListConfigData() {
        Checklist_Instance__c checklistInstance = [SELECT Id FROM Checklist_Instance__c LIMIT 1];
        Test.startTest();
        Object configData = CL_ChecklistController.getCheckListConfigData(checklistInstance.Id);
        Map<String, Object> deserializedMap = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(configData));
        Test.stopTest();
        Assert.IsTrue(Boolean.ValueOf(deserializedMap.get('isSuccess')), 'The config data should be successful.');
    }

    @isTest
    static void testGetCheckListConfigDataWithError() {
        Test.startTest();
        Object configData = CL_ChecklistController.getCheckListConfigData('12345');
        Map<String, Object> deserializedMap = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(configData));
        Test.stopTest();
        Assert.IsFalse(Boolean.ValueOf(deserializedMap.get('isSuccess')), 'The config data should be failed.');
    }

    @isTest
    static void testGetSectionList() {
        Checklist_Instance__c checklistInstance = [SELECT Id FROM Checklist_Instance__c LIMIT 1];
        Test.startTest();
        Object configData = CL_ChecklistController.getSectionList(checklistInstance.Id);
        Map<String, Object> deserializedMap = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(configData));
        Test.stopTest();
        Assert.IsTrue(Boolean.ValueOf(deserializedMap.get('isSuccess')), 'The config data should be successful.');
    }

    @isTest
    static void testGetSectionListWithError() {
        Test.startTest();
        Object configData = CL_ChecklistController.getSectionList('12345');
        Map<String, Object> deserializedMap = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(configData));
        Test.stopTest();
        Assert.IsFalse(Boolean.ValueOf(deserializedMap.get('isSuccess')), 'The config data should be failed.');
    }

    @isTest
    static void testGetSubSectionList() {
        Checklist_Instance__c checklistInstance = [SELECT Id FROM Checklist_Instance__c LIMIT 1];
        Checklist_Section__c section = [SELECT Id FROM Checklist_Section__c WHERE Name = 'Parent Section' LIMIT 1];
        Test.startTest();
        Object configData = CL_ChecklistController.getSubSectionList(checklistInstance.Id, section.Id);
        Map<String, Object> deserializedMap = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(configData));
        Test.stopTest();
        Assert.IsTrue(Boolean.ValueOf(deserializedMap.get('isSuccess')), 'The config data should be successful.');
    }
}