force-app/main/default/objects/iManage_Setting__c/iManage_Setting__c.object-meta.xml
<CustomObject>
    <label>iManage Setting</label>
    <nameField>
        <displayFormat>IFN-{000000}</displayFormat>
        <label>iManage Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>iManage Setting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/iManage_Setting__c/fields/Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>Folder_Id__c</fullName>
    <label>Folder_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/iManage_Workspace__c/iManage_Workspace__c.object-meta.xml
<CustomObject>
    <label>iManage Workspace</label>
    <nameField>
        <displayFormat>IMW-{000000}</displayFormat>
        <label>iManage Workspace Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>iManage Workspace</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/iManage_Workspace__c/fields/custom10__c.field-meta.xml
<CustomField>
    <fullName>custom10__c</fullName>
    <label>custom10</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/iManage_Workspace__c/fields/custom1__c.field-meta.xml
<CustomField>
    <fullName>custom1__c</fullName>
    <label>custom1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/iManage_Workspace__c/fields/custom2__c.field-meta.xml
<CustomField>
    <fullName>custom2__c</fullName>
    <label>custom2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/iManage_Workspace__c/fields/custom3__c.field-meta.xml
<CustomField>
    <fullName>custom3__c</fullName>
    <label>custom3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/iManage_Workspace__c/fields/custom4__c.field-meta.xml
<CustomField>
    <fullName>custom4__c</fullName>
    <label>custom4</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/iManage_Workspace__c/fields/custom5__c.field-meta.xml
<CustomField>
    <fullName>custom5__c</fullName>
    <label>custom5</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/iManage_Workspace__c/fields/custom6__c.field-meta.xml
<CustomField>
    <fullName>custom6__c</fullName>
    <label>custom6</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/iManage_Workspace__c/fields/custom7__c.field-meta.xml
<CustomField>
    <fullName>custom7__c</fullName>
    <label>custom7</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/iManage_Workspace__c/fields/custom8__c.field-meta.xml
<CustomField>
    <fullName>custom8__c</fullName>
    <label>custom8</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/iManage_Workspace__c/fields/custom9__c.field-meta.xml
<CustomField>
    <fullName>custom9__c</fullName>
    <label>custom9</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/iManage_Workspace__c/fields/id__c.field-meta.xml
<CustomField>
    <fullName>id__c</fullName>
    <label>id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/cmpAPiMngSearchFolderBatch.cls
/*
*********************************************************
Apex Class Name    : cmpAPiMngSearchFolderBatch
Created Date       : July 12, 2023
@description       : API3, search folders from in the workspace
@author            : Amar P
Modification Log:
Ver   Date         Author                               Modification
1.0   07-2023   Amar P                      			Initial Version
*********************************************************
*/

global class cmpAPiMngSearchFolderBatch implements Database.AllowsCallouts,Database.Batchable<sObject>,Schedulable,Database.Stateful {
    
    //List<string> m_recordId = new List<string>();
    //m_recordId.add('MB_SB!90');
   //cmpAPiMngSearchFolderBatch AwardDeclined = NEW cmpAPiMngSearchFolderBatch(m_recordId);
   //database.executeBatch(AwardDeclined, 1); 
   public List<string> m_recordId = new List<string>();
   public string query='';
   public string access_token='';
    
    Public cmpAPiMngSearchFolderBatch(List<string> recordId) {
        m_recordId=recordId;
     	query='SELECT Id,id__c,custom1__c,custom2__c,custom3__c,custom4__c,custom5__c,custom6__c,custom7__c,custom8__c,custom9__c,custom10__c ';
        query+=' FROM iManage_Workspace__c Where id__c IN:m_recordId AND custom1__c!=null';
        system.debug('query ' + query);
      
        access_token=cmpAPAPIHeaderCtrl.getToken();
  	}
    
    
    public Database.QueryLocator start(Database.BatchableContext context) {
        
        return Database.getQueryLocator(query);
    }

   
    public void execute(Database.BatchableContext context, List<iManage_Workspace__c>  records) {
        if(records.size()>0) {
           for(iManage_Workspace__c data :records) { 
               if(data.custom1__c!=null && data.custom1__c!='')
                   cmpAPiMngSearchFolderWorkspaceCtrl.iMngSearchworkspaceFolder(access_token,data.id__c);
            }
       }
      
   }

    global void execute(SchedulableContext ctx)  {
        Database.executeBatch(this);
    }
    
    global void finish(Database.BatchableContext bc) {
         List<string> m_recordId = new List<string>();
         List<iManage_Setting__c> ObjWorkspaces = cmpAPAPIHeaderCtrl.getiManageFoldersToBeSynced();
         if (ObjWorkspaces.size()>0) { 
             for(iManage_Setting__c data :ObjWorkspaces) { 
                 m_recordId.add(data.Folder_Id__c);
             }
         }
        
        if(m_recordId.size()>0){
            if(!test.isRunningTest()) {
   				cmpAPiMngSearchFolderUpdatedBatch AwardDeclined = NEW cmpAPiMngSearchFolderUpdatedBatch(m_recordId);
   				database.executeBatch(AwardDeclined, 1); 
            }
        }
        
    }
    
    
}