force-app/main/default/objects/DocuSign__c/DocuSign__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>DocuSign</label>
</CustomObject>

force-app/main/default/objects/DocuSignReviewer__c/DocuSignReviewer__c.object-meta.xml
<CustomObject>
    <label>DocuSignReviewer</label>
    <nameField>
        <displayFormat>DSR-{000000}</displayFormat>
        <label>DocuSignReviewer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSignReviewer</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DocuSignReviewer__c/fields/Inventor_Name__c.field-meta.xml
<CustomField>
    <fullName>Inventor_Name__c</fullName>
    <label>Inventor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocuSignReviewer__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocuSignReviewer__c/fields/RecipientId__c.field-meta.xml
<CustomField>
    <fullName>RecipientId__c</fullName>
    <label>RecipientId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DocuSignReviewer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>sent</fullName>
            </value>
            <value>
                <fullName>created</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cmpAPDocuSignCreateSignHereTabs.cls
global class cmpAPDocuSignCreateSignHereTabs implements Database.Batchable <sObject>, Database.AllowsCallouts, Database.Stateful  {
    Public List<string> completedRecords{set;get;}
    public string Reviewer_Id{set;get;}
    public string query{set;get;}
    public string envelopeid{set;get;}
    public string Person_Id{set;get;}
    
    global cmpAPDocuSignCreateSignHereTabs(string ReviewerId, string envelope_id) {
        Reviewer_Id=ReviewerId;
        envelopeid=envelope_id;
        
        system.debug('Reviewer_Id' + Reviewer_Id);
        
        query = 'SELECT Id,Person__c,Email__c,Status__c,RecipientId__c,Inventor_Name__c FROM DocuSignReviewer__c Where  Id=:Reviewer_Id ';
        
        system.debug('query' + query);
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        system.debug('query :'+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<DocuSignReviewer__c> records) {
        string apiHeader = cmpAPDocuSignHelper.getHeader(); 
        string apiBody = '';
        string responseBody = '';
        string signHereTabs='';
        integer recipientId=2;
       
         if (records.size()>0) {
             for(DocuSignReviewer__c recipients : records ) {
               		recipientId=integer.valueOf(recipients.RecipientId__c);
                    if(recipientId==null)
                        recipientId=1;
                        
                  if (signHereTabs == '') {
                      signHereTabs = '{';
                      signHereTabs += '"signHereTabs":[';
                      signHereTabs += cmpAPDocuSignHelper.getSignHereTabAnchorString('1', string.valueOf(recipientId).replaceall('.0',''),recipients.Inventor_Name__c, '', '','');    
                  } else {
                      signHereTabs += ', ' + cmpAPDocuSignHelper.getSignHereTabAnchorString('1', string.valueOf(recipientId).replaceall('.0',''),recipients.Inventor_Name__c, '', '', '');     
                  }
        
        signHereTabs += ']';
        signHereTabs += '}';
        apiBody=signHereTabs;
        
        string apiBodyLength = String.valueOf(apiBody.length());
        System.debug('apiBody' + apiBody);         
        DocuSign__c objCSDocuSign = DocuSign__c.getInstance('Default');
        HttpRequest req = new HttpRequest();
        string endpoint=objCSDocuSign.EndPoint__c + objCSDocuSign.AccountNumber__c + '/envelopes/' + envelopeid + '/recipients/'+ string.valueOf(recipientId).replaceall('.0','') + '/tabs';         
        system.debug('endpoint' + endpoint);
        req.setEndpoint(endpoint);
        req.setMethod('POST');  
        
        if (apibody.trim()!='') {
            req.setBody(apibody);
            req.setHeader('Content-length', apiBodyLength);
        }
        req.setHeader('Content-type', 'application/json');
        req.setHeader('X-DocuSign-Authentication', apiHeader );
        req.setTimeout(120000);
        Http http = new Http();
        if(!test.isRunningTest()) {
            
       			try {
                     	HTTPResponse httpResponse = http.send(req);
                    	System.debug('httpResponse()' + httpResponse.getBody());
                     	System.debug('getStatusCode()' + httpResponse.getStatusCode());
                    
                     if(httpResponse.getStatusCode() == 200 || httpResponse.getStatusCode() == 201) {
                       recipientId=recipientId+1;
                     }
                    
                  }
                    catch(Exception exp) {
                        
      				}
            
    	}
        
      }
   }
}
    
    global void finish(Database.BatchableContext bc){

    }    
}