force-app/main/default/objects/DocuSign__c/DocuSign__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>DocuSign</label>
</CustomObject>

force-app/main/default/objects/DocuSign__c/fields/IntegratorKey__c.field-meta.xml
<CustomField>
    <fullName>IntegratorKey__c</fullName>
    <label>IntegratorKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocuSign__c/fields/TokenUrl__c.field-meta.xml
<CustomField>
    <fullName>TokenUrl__c</fullName>
    <label>TokenUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocuSign__c/fields/UserPassword__c.field-meta.xml
<CustomField>
    <fullName>UserPassword__c</fullName>
    <label>UserPassword</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocuSignSetting__c/DocuSignSetting__c.object-meta.xml
<CustomObject>
    <label>DocuSignSetting</label>
    <nameField>
        <displayFormat>DSN-{00000}</displayFormat>
        <label>DocuSignSetting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSignSetting</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DocuSignSetting__c/fields/access_token__c.field-meta.xml
<CustomField>
    <fullName>access_token__c</fullName>
    <label>access token</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DocuSignSetting__c/fields/refresh_token__c.field-meta.xml
<CustomField>
    <fullName>refresh_token__c</fullName>
    <label>refresh token</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/cmpAPDocuSignTokenCtrlTest.cls
@isTest
private class cmpAPDocuSignTokenCtrlTest {

    static testMethod void myTestMethod() {  
        
        DocuSign__c ds = new DocuSign__c(name='Default',
                                         UserName__c = 'amar.p@maxval.com',
                                         UserPassword__c='f$J6sQ*pa#zt@6.',
                                         EndPoint__c='https://demo.docusign.net/restapi/v2/accounts/',
                                         IntegratorKey__c='97fe8b93-7601-48d2-acf5-e62932febef2',
                                         TokenUrl__c ='https://account-d.docusign.com/oauth/token',
                                         Authorization__c='Basic OTdmZThiOTMtNzYwMS00OGQyLWFjZjUtZTYyOTMyZmViZWYyOjRhMzdlZWQ2LThiYTEtNDcwNi05MzAxLWJjMDZjNDgzYTFjMw==');
        insert ds;
        
        List<DocuSignSetting__c> tstCont = new List<DocuSignSetting__c>();
        DocuSignSetting__c Person = new DocuSignSetting__c();
        Person.access_token__c = '';
        Person.refresh_token__c ='';
        tstCont.add(Person);
		insert Person;
        
         test.starttest();
        	cmpAPDocuSignTokenCtrl.setHeader(Person.Id,'', '');
        	cmpAPDocuSignTokenCtrl.getToken();
        	cmpAPDocuSignTokenCtrl.getRefreshToken();
        	cmpAPDocuSignTokenCtrl.DocuSignTokenFuture();
         test.stopTest();
    }
}