force-app/main/default/objects/DocuSign__c/DocuSign__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>DocuSign</label>
</CustomObject>

force-app/main/default/objects/DocuSignReviewer__c/DocuSignReviewer__c.object-meta.xml
<CustomObject>
    <label>DocuSignReviewer</label>
    <nameField>
        <displayFormat>DSR-{000000}</displayFormat>
        <label>DocuSignReviewer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSignReviewer</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DocuSignReviewer__c/fields/Inventor_Name__c.field-meta.xml
<CustomField>
    <fullName>Inventor_Name__c</fullName>
    <label>Inventor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocuSignReviewer__c/fields/IsDocuSign__c.field-meta.xml
<CustomField>
    <fullName>IsDocuSign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsDocuSign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DocuSignReviewer__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocuSignReviewer__c/fields/RecipientId__c.field-meta.xml
<CustomField>
    <fullName>RecipientId__c</fullName>
    <label>RecipientId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DocuSignReviewer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>sent</fullName>
            </value>
            <value>
                <fullName>created</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EnvelopeInfo__c/EnvelopeInfo__c.object-meta.xml
<CustomObject>
    <label>EnvelopeInfo</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>EnvelopeInfo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EnvelopeInfo</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EnvelopeInfo__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <label>Attachment_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnvelopeInfo__c/fields/Certificate_Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Attachment_Id__c</fullName>
    <label>Certificate Attachment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnvelopeInfo__c/fields/DownloadStatus__c.field-meta.xml
<CustomField>
    <fullName>DownloadStatus__c</fullName>
    <label>DownloadStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EnvelopeInfo__c/fields/EnvelopeId__c.field-meta.xml
<CustomField>
    <fullName>EnvelopeId__c</fullName>
    <label>EnvelopeId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnvelopeInfo__c/fields/Error_Count_on_Fetch_Status__c.field-meta.xml
<CustomField>
    <fullName>Error_Count_on_Fetch_Status__c</fullName>
    <label>Error_Count_on_Fetch_Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EnvelopeInfo__c/fields/Error_Occurred__c.field-meta.xml
<CustomField>
    <fullName>Error_Occurred__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Error_Occurred</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EnvelopeInfo__c/fields/Error_on_Status_Fetch__c.field-meta.xml
<CustomField>
    <fullName>Error_on_Status_Fetch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Error_on_Status_Fetch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EnvelopeInfo__c/fields/Error_Text__c.field-meta.xml
<CustomField>
    <fullName>Error_Text__c</fullName>
    <label>Error_Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnvelopeInfo__c/fields/Error_Text_on_Status_Fetch__c.field-meta.xml
<CustomField>
    <fullName>Error_Text_on_Status_Fetch__c</fullName>
    <label>Error_Text_on_Status_Fetch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnvelopeInfo__c/fields/Receivers__c.field-meta.xml
<CustomField>
    <fullName>Receivers__c</fullName>
    <label>Receivers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnvelopeInfo__c/fields/Sent_On__c.field-meta.xml
<CustomField>
    <fullName>Sent_On__c</fullName>
    <label>Sent On</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnvelopeInfo__c/fields/SignedAssignment__c.field-meta.xml
<CustomField>
    <fullName>SignedAssignment__c</fullName>
    <label>SignedAssignment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnvelopeInfo__c/fields/SignedOathDeclaration__c.field-meta.xml
<CustomField>
    <fullName>SignedOathDeclaration__c</fullName>
    <label>SignedOathDeclaration</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnvelopeInfo__c/fields/Status_Fetched_on__c.field-meta.xml
<CustomField>
    <fullName>Status_Fetched_on__c</fullName>
    <label>Status Fetched on</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/cmpAPDocuSignCompletionCertificate.cls
global with sharing class cmpAPDocuSignCompletionCertificate {

    
    @AuraEnabled
    public static void SetAdhocReminder(string envelope_id,string ReminderDelay,string ReminderFrequency,string ExpireAfter,string ExpireWarn)  {
       
        string apiHeader = cmpAPDocuSignHelper.getHeader(); 
        string apiBody = '';
        string responseBody = '';
        integer recipientId=2;
        boolean IsSent=false;
       
        string Qstr = '{';
            Qstr += '"useAccountDefaults": "false",';
            Qstr += '"reminders": {';
            Qstr += '"reminderEnabled":"true",';
            Qstr += '"reminderDelay":"' + ReminderDelay + '",';
            Qstr += '"reminderFrequency":"' + ReminderFrequency + '"';
            Qstr += '},';
            Qstr += '"expirations": {';
            Qstr += '"expireEnabled":"true",';
            Qstr += '"expireAfter":"' + ExpireAfter + '",';
            Qstr += '"expireWarn":"' + ExpireWarn + '"';
            Qstr += '}';
        	Qstr += '}';
        
        apiBody=Qstr;
        system.debug('apiBody ' + apiBody);
        
        string apiBodyLength = String.valueOf(apiBody.length());
        DocuSign__c objCSDocuSign = DocuSign__c.getInstance('Default');
        HttpRequest req = new HttpRequest();
        req.setEndpoint(objCSDocuSign.EndPoint__c + objCSDocuSign.AccountNumber__c + '/envelopes/' + envelope_id + '/notification');
        req.setMethod('PUT');  
        req.setBody(apibody);
        req.setHeader('Content-length', apiBodyLength);
        req.setHeader('Content-type', 'application/json');
        req.setHeader('Authorization', 'Bearer ' + apiHeader );
        req.setTimeout(120000);
        Http http = new Http();
        if(!test.isRunningTest()) {
            
       			try {
                     HTTPResponse httpResponse = http.send(req); 
                     system.debug('response-->'+ httpResponse.getBody());
                  }  catch(Exception exp) {
                        
      			  }
    	}
 }
    
    @AuraEnabled
    public static void SetReminder(string envelope_id)  {
       
        string apiHeader = cmpAPDocuSignHelper.getHeader(); 
        string apiBody = '';
        string responseBody = '';
        string signHereTabs='';
        integer recipientId=2;
        boolean IsSent=false;
       
        signHereTabs = '{';
        signHereTabs += cmpAPDocuSignHelper.getdocusignreminder();
        signHereTabs += '}';
        apiBody=signHereTabs;
        
        string apiBodyLength = String.valueOf(apiBody.length());
        DocuSign__c objCSDocuSign = DocuSign__c.getInstance('Default');
        HttpRequest req = new HttpRequest();
        req.setEndpoint(objCSDocuSign.EndPoint__c + objCSDocuSign.AccountNumber__c + '/envelopes/' + envelope_id + '/notification');
        req.setMethod('PUT');  
        
        if (apibody.trim()!='') {
            req.setBody(apibody);
            req.setHeader('Content-length', apiBodyLength);
        }
        req.setHeader('Content-type', 'application/json');
        req.setHeader('Authorization', 'Bearer ' + apiHeader );
        req.setTimeout(120000);
        Http http = new Http();
        if(!test.isRunningTest()) {
            
       			try {
                     HTTPResponse httpResponse = http.send(req);   
                  }  catch(Exception exp) {
                        
      			  }
    	}
 }
    
    @AuraEnabled
    public static void CreateSignHereTabs(string PatentID, string envelope_id, string PersonId) {
       
        string apiHeader = cmpAPDocuSignHelper.getHeader(); 
        string apiBody = '';
        string responseBody = '';
        string signHereTabs='';
        integer recipientId=2;
        List<DocuSignReviewer__c> DocuSignReviewers = [SELECT Person__c,Email__c,RecipientId__c 
                                                       FROM DocuSignReviewer__c 
                                                       Where recordId__c = : PatentID 
                                                       AND IsDocuSign__c=true];
         if (DocuSignReviewers.size()>0) {
             for(DocuSignReviewer__c recipients : DocuSignReviewers ) {
              	  cmpAPDocuSignCreateSignHereTabs CreateSignHereTabs = NEW cmpAPDocuSignCreateSignHereTabs(recipients.Id,envelope_id);
        		  database.executeBatch(CreateSignHereTabs, 1); 
     	}
   	}   
        
        
 }
    
    @AuraEnabled
    public static void Sendrecipients(string PatentID, string envelope_id, string PersonId) {
       
        string apiHeader = cmpAPDocuSignHelper.getHeader(); 
        string apiBody = '';
        string responseBody = '';
        string signHereTabs='';
        integer recipientId=2;
        boolean IsSent=false;
        List<DocuSignReviewer__c> SignReviewers = new List<DocuSignReviewer__c>();
        
        List<DocuSignReviewer__c> DocuSignReviewers = [SELECT Id,Person__c,Inventor_Name__c,Email__c,Status__c,RecipientId__c 
                                                       FROM DocuSignReviewer__c 
                                                       Where recordId__c = : PatentID 
                                                       AND IsDocuSign__c=true];
         if (DocuSignReviewers.size()>0) {
             for(DocuSignReviewer__c recipients : DocuSignReviewers ) {
                 cmpAPDocuSignRecipients BatchRecipients = NEW cmpAPDocuSignRecipients(recipients.Id,envelope_id);
        		 database.executeBatch(BatchRecipients, 1);
                 
      		}
    	}
      
        
 }
    
    Public static void getEnvelopecertificates(string PatentID, string envelope_id) {
          String returnmessage ='';
        List<EnvelopeInfo__c> objEnvelopes = [SELECT Name, EnvelopeId__c, Sent_On__c, Status__c,Status_Fetched_on__c, Receivers__c, 
                                              Attachment_Id__c, Certificate_Attachment_Id__c, SignedAssignment__c, SignedOathDeclaration__c,Error_Occurred__c,
                                              Error_Text__c, Error_Text_on_Status_Fetch__c,Error_on_Status_Fetch__c,
                                              Error_Count_on_Fetch_Status__c 
                                              FROM EnvelopeInfo__c 
                                              Where EnvelopeId__c =: envelope_id];
         if (objEnvelopes.size() > 0) {
             for(EnvelopeInfo__c record : objEnvelopes ) {
               getEnvelopeAttachment(envelope_id,record.Id);   
             }
         }
     }
    
    @AuraEnabled
    public static void getEnvelopeAttachment(string envelopeId, string envelopeSFId) {
        try 
        {
            system.debug('envelopeId :'+envelopeId+'|envelopeSFId :'+envelopeSFId+'');
            string apiHeader = cmpAPDocuSignHelper.getHeader(); 
            
            DocuSign__c objCSDocuSign = DocuSign__c.getInstance('Default');
            HttpRequest req = new HttpRequest();
            req.setEndpoint(objCSDocuSign.EndPoint__c + objCSDocuSign.AccountNumber__c + '/envelopes/' + envelopeId + '/documents/certificate');
            req.setMethod('GET');  
            req.setHeader('Content-type', 'application/json');
            req.setHeader('Authorization', 'Bearer ' + apiHeader );
            req.setTimeout(120000);
            
            Http http = new Http();
            if(!test.isRunningTest())
            {
                string errortext='';
                EnvelopeInfo__c objEnvelope = [SELECT Id, Name, Status__c, Attachment_Id__c, Certificate_Attachment_Id__c FROM EnvelopeInfo__c WHERE Id=:envelopeSFId LIMIT 1];
                if (objEnvelope != null)
                {
                    try
                    {
                        
                        HTTPResponse httpResponse = http.send(req);
                        if(httpResponse.getStatusCode() == 200 || httpResponse.getStatusCode() == 201) {
                            Blob contentFile= httpResponse.getBodyAsBlob();
                            string strContent = EncodingUtil.base64Encode(contentFile);
                            
                            ContentVersion cv = new ContentVersion();
                            cv.ContentLocation = 'S';
                            cv.VersionData = EncodingUtil.base64Decode(strContent);
                            cv.Title = 'Completion Certificate';
                            cv.PathOnClient = 'Completion Certificate.pdf'; 
                            INSERT cv;
                            
                            
                            ContentDocumentLink link = new ContentDocumentLink();
                            link.LinkedEntityId = envelopeSFId;
                            link.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
                            link.ShareType = 'V';
                            link.Visibility = 'AllUsers';
                            INSERT link;
                           
                            objEnvelope.Certificate_Attachment_Id__c = cv.Id;
                           
                        } 
                    }
                    catch(exception e)
                    {
                        objEnvelope.DownloadStatus__c = 'Pending';
                        
                    }
                    
                    UPDATE objEnvelope;
                }
                
            }
            
            
            			if(test.isRunningTest()){
                            string strContent ='192301931212310';
                            
                            ContentVersion cv = new ContentVersion();
                            cv.ContentLocation = 'S';
                            cv.VersionData = EncodingUtil.base64Decode(strContent);
                            cv.Title = 'Completion Certificate';
                            cv.PathOnClient = 'Completion Certificate.pdf'; 
                            INSERT cv;
                            
                            
                            ContentDocumentLink link = new ContentDocumentLink();
                            link.LinkedEntityId = envelopeSFId;
                            link.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
                            link.ShareType = 'V';
                            link.Visibility = 'AllUsers';
                            INSERT link;
                
            }
        }
        catch(Exception exp) {
            system.debug('SignReviewers' + exp.getStackTraceString() );
        }
        
       
    }
    
    
}