force-app/main/default/objects/iManage_Documents__c/iManage_Documents__c.object-meta.xml
<CustomObject>
    <label>iManage Documents</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>iManage Documents#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>iManage Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/iManage_Documents__c/fields/document_number__c.field-meta.xml
<CustomField>
    <fullName>document_number__c</fullName>
    <label>document_number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/iManage_Documents__c/fields/iManage_Folders__c.field-meta.xml
<CustomField>
    <fullName>iManage_Folders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>iManage Folders</label>
    <referenceTo>iManage_Folders__c</referenceTo>
    <relationshipLabel>iManage Documents</relationshipLabel>
    <relationshipName>iManage_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/iManage_Folders__c/iManage_Folders__c.object-meta.xml
<CustomObject>
    <label>iManage Folders</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>iManage Folders#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>iManage Folders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/cmpAPiMngDocketingEmailsBatch.cls
public class cmpAPiMngDocketingEmailsBatch implements Database.AllowsCallouts,Database.Batchable<SObject> {
    public List<string> iManageDocumentIds;
    public String PatentId;
    public String access_token;
	public String iManageEmailId;
    public List<string> DocketingActivitiesIds;
    
    public cmpAPiMngDocketingEmailsBatch(List<string> iManageDocumentIds, String PatentId,List<string> DocketingActivitiesIds, String iManageEmailId) {
        this.iManageDocumentIds = iManageDocumentIds;
        this.PatentId = PatentId;
        this.DocketingActivitiesIds = DocketingActivitiesIds;
        this.iManageEmailId = iManageEmailId;
        
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        this.access_token=cmpAPAPIHeaderCtrl.getToken();
        String query = 'SELECT Id, id__c, ContentVersionId__c, iManage_Folders__c, document_number__c, CreatedDate ' + 
                       'FROM iManage_Documents__c ' +
                       'WHERE Id IN :iManageDocumentIds ' + 
                       'ORDER BY CreatedDate DESC ' + 
                       'LIMIT 100';
        
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<iManage_Documents__c> scope) {
        if (scope.size() > 0) {
            for (iManage_Documents__c Data : scope) {
                if (PatentId != null && PatentId != '' && Data.id__c != null && Data.id__c != '') {
                    cmpAPiMangDownloadDocCtrl.iMngDownloadDocument(access_token, Data.id__c, PatentId);
                }
            }
        }
    }

    public void finish(Database.BatchableContext BC) {
        cmpAPiMngDocketingEmailsSendBatch batch = new cmpAPiMngDocketingEmailsSendBatch(iManageDocumentIds,PatentId,DocketingActivitiesIds,iManageEmailId);
        Database.executeBatch(batch, 1);
    }
}