force-app/main/default/objects/API_Details__c/API_Details__c.object-meta.xml
<CustomObject>
    <label>API Details</label>
    <nameField>
        <displayFormat>API-{000000}</displayFormat>
        <label>API Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Details__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>API-1</fullName>
            </value>
            <value>
                <fullName>ServiceNow</fullName>
            </value>
            <value>
                <fullName>API4</fullName>
            </value>
            <value>
                <fullName>API3</fullName>
            </value>
            <value>
                <fullName>API2</fullName>
            </value>
            <value>
                <fullName>API5</fullName>
            </value>
            <value>
                <fullName>API6</fullName>
            </value>
            <value>
                <fullName>API7</fullName>
            </value>
            <value>
                <fullName>API10</fullName>
            </value>
            <value>
                <fullName>API11</fullName>
            </value>
            <value>
                <fullName>API12</fullName>
            </value>
            <value>
                <fullName>API13</fullName>
            </value>
            <value>
                <fullName>API15</fullName>
            </value>
            <value>
                <fullName>API16</fullName>
            </value>
            <value>
                <fullName>API20</fullName>
            </value>
            <value>
                <fullName>API23</fullName>
            </value>
            <value>
                <fullName>API8</fullName>
            </value>
            <value>
                <fullName>API17</fullName>
            </value>
            <value>
                <fullName>API24</fullName>
            </value>
            <value>
                <fullName>API21</fullName>
            </value>
            <value>
                <fullName>iMngCreateWorkSpace</fullName>
            </value>
            <value>
                <fullName>API1</fullName>
            </value>
            <value>
                <fullName>API9</fullName>
            </value>
            <value>
                <fullName>iMngRenamed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Details__c/fields/ContentVersionId__c.field-meta.xml
<CustomField>
    <fullName>ContentVersionId__c</fullName>
    <label>ContentVersionId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Details__c/fields/createdFolderId__c.field-meta.xml
<CustomField>
    <fullName>createdFolderId__c</fullName>
    <label>createdFolderId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Details__c/fields/iManage_Documents__c.field-meta.xml
<CustomField>
    <fullName>iManage_Documents__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>iManage Documents</label>
    <referenceTo>iManage_Documents__c</referenceTo>
    <relationshipLabel>API Details</relationshipLabel>
    <relationshipName>API_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Details__c/fields/iManageFoldersId__c.field-meta.xml
<CustomField>
    <fullName>iManageFoldersId__c</fullName>
    <label>iManageFoldersId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Details__c/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <label>recordId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Details__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sync Start</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/iManage_Documents__c/iManage_Documents__c.object-meta.xml
<CustomObject>
    <label>iManage Documents</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>iManage Documents#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>iManage Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/iManage_Documents__c/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <formula>iManage_Folders__r.recordId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>recordId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/cmpAPiMngFailedBatch.cls
/*
*********************************************************
Apex Class Name    : cmpAPiMngFailedBatch
Created Date       : 07 Jan, 2024
@description       : re- Sync failed request....
@author            : Amar P
Modification Log:
Ver   Date      Author                               Modification
1.0   01-2024   Amar P                      		 Initial Version
*********************************************************
*/

global class cmpAPiMngFailedBatch implements Database.AllowsCallouts,Database.Batchable<Sobject>,Schedulable,Database.Stateful {
 	public string query{set;get;}
    public string Approval_Status{set;get;}
    public boolean isSuccess;
    
    //cmpAPiMngFailedBatch docuSign=new cmpAPiMngFailedBatch();
    //Database.executeBatch(docuSign,1);
	//System.schedule('cmpAPiMngFailedBatch Every 0th min', '0 0 * * * ?', new cmpAPiMngFailedBatch());
	//System.schedule('cmpAPiMngFailedBatch-Every 15th', '0 1 0 15 * ? *', new cmpAPiMngFailedBatch());
	
    Public cmpAPiMngFailedBatch() {
      
      Approval_Status='Success';
      query='';
      query += ' Select Id,API_Name__c,ContentVersionId__c,createdFolderId__c,iManage_Documents__c,iManageFoldersId__c,';
      query += ' recordId__c,Status__c,Sync_Status__c';
      query += ' From API_Details__c ';
      query += ' Where Status__c!=:Approval_Status Order by CreatedDate DESC Limit 10';
      system.debug('query ' + query);
   
      
  }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {

        return Database.getQueryLocator(query);

    }

    global void execute(Database.BatchableContext bc, List<API_Details__c> scope) {

            for (API_Details__c data : scope)  {
                if(data.API_Name__c=='API8'){
                    cmpAPiManagDocumentCtrl.UploadDocumentAPIDetailsBatch(data.createdFolderId__c,data.ContentVersionId__c, data.iManageFoldersId__c);
                }     
            }

    }    

    global void execute(SchedulableContext ctx)  {
        Database.executeBatch(this);
    }
    
    global void finish(Database.BatchableContext bc){   
    
    }    

}